cart/urls.py
from django.urls import path
from django.conf.urls import url
from cart import views
app_name = 'cart'

urlpatterns = [
    path('cart_add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart_remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('cart_detail/', views.cart_detail, name='cart_detail'),
    # url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    # url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),
    # url(r'^cart_detail/$',views.cart_detail,name='cart_detail'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mystore.views import *
app_name = 'mystore'


urlpatterns = [
    path('detail/<int:id>/', product_detail, name='product_detail'),
    path('tao-cookie/', tao_cookie, name='tao-cookie'),
    path('doc-cookie/', doc_cookie, name='doc-cookie'),
    path('xoa-cookie/', xoa_cookie, name='xoa-cookie'),
]

shoponline/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from mystore import views
from cart import urls

urlpatterns = [
    path('', views.index, name='index'),
    path('mystore/', include('mystore.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

mystore/models.py
from django.db import models
# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=200,unique=True)
    fee = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to = "images/")
    def __str__(self):
        return str(self.name)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]
class CardAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label= 'Số lượng', choices =
    PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required = False, widget = forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mystore.models import Product
from cart.cart import Cart
from cart.forms import CardAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id=None):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    form = CardAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product = product, quantity = cd['quantity'], update_quantity = cd['update'])
    print(cart)
    
    
    return redirect('cart:cart_detail')

def cart_remove(request, product_id=None):
    cart = Cart(request)
    print(cart)
    product = get_object_or_404(Product, id = product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CardAddProductForm(initial = {'quantity':item['quantity'], 'update': True } )
    return render(request, 'cart/cart_detail.html', {'cart':cart})

mystore/views.py
from django.shortcuts import render
from mystore.models import Product
from datetime import datetime
from cart.forms import CardAddProductForm

# Create your views here.

def index(request):
    pro_list = Product.objects.order_by('name')
    pro_dict = {"products":pro_list }
    return render(request, "mystore/index.html", context=pro_dict)
def product_detail(request, id=None):
    product = Product.objects.get(pk=id)
    cart_product_form = CardAddProductForm()
    return render(request, 'mystore/product_detail.html', context= {'product': product, 'cart_product_form': cart_product_form })
def tao_cookie(request):
    response = render(request, 'mystore/tao_cookie.html')
    date1 = datetime.now()
    response.set_cookie('last_visit', date1.strftime('%d-%m-%Y %H:%M:%S'))
    return response

def doc_cookie(request):
    value = request.COOKIES.get('last_visit')
    text = '<h2> lần cuối truy cập là  %s </h2>' %value
    return render(request, 'mystore/doc_cookie.html', {'text':text})
def xoa_cookie(request):
    response = render(request, 'mystore/tao_cookie.html')
    response.delete_cookie('last_visit')
    return response

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

    <!-- meta data & title -->
    <meta charset="utf-8">
    <title>Office</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="{% static 'assets/ico/favicon.ico' %} ">
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
        href="{% static 'assets/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
        href="{% static 'assets/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
        href="{% static 'assets/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'assets/ico/apple-touch-icon-57-precomposed.png' %}">

    <!-- CSS -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

</head>

<body>

    <!-- Header -->

    <nav id="navbar-section" class="navbar navbar-default navbar-static-top navbar-sticky" role="navigation">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target=".navbar-responsive-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand wow fadeInDownBig" href="{% url 'index' %}"><img class="office-logo"
                        src="{% static 'assets/img/slider/Office.png' %}" alt="Office"></a>
            </div>

            {% comment %} <div id="navbar-spy" class="collapse navbar-collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav pull-right">
                    <li class="active">
                        <a href=" {% url 'index' %} ">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="blog.html">Blog</a>
                    </li>
                    <li>
                        <a href="team.html">Team</a>
                    </li>
                    <li>
                        <a href="contact.html"><span>Contact</span></a>
                    </li>
                </ul>
            </div> {% endcomment %}
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'index' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'cart:cart_detail'%}">Cart<img src="{% static 'images/cart.png' %}"
                            style="width: 40px; margin-top: 0px;" /></a>
                        <!-- <a class="nav-link" href="{% url 'cart:cart_detail'%}"><img src="{% static 'images/cart.png' %}"
                                style="width: 40px; margin-top: 0px;" /></a> -->
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- End Header -->

    <div class="container">
        {% block body_block %}
        <!-- Anything outsite of this will be inherited if you extend! -->
        {% endblock %}
    </div>



    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h3><i class="fa fa-map-marker"></i> Contact:</h3>
                    <p class="footer-contact">
                        Via Ludovisi 39-45, Rome, 54267, Italy<br>
                        Phone: 1.800.245.356 Fax: 1.800.245.357<br>
                        Email: hello@LawOffice.org<br>
                    </p>
                </div>
                <div class="col-md-4">
                    <h3><i class="fa fa-external-link"></i> Links</h3>
                    <p> <a href="#"> About ( Who we are )</a></p>
                    <p> <a href="#"> Services ( What we do )</a></p>
                    <p> <a href="#"> Contact ( Feel free to contact )</a></p>
                    <p> <a href="#"> Blog ( Write to us )</a></p>
                    <p> <a href="#"> Team ( Meet the Team )</a></p>
                </div>
                <div class="col-md-4">
                    <h3><i class="fa fa-heart"></i> Socialize</h3>
                    <div id="social-icons">
                        <a href="#" class="btn-group google-plus">
                            <i class="fa fa-google-plus"></i>
                        </a>
                        <a href="#" class="btn-group linkedin">
                            <i class="fa fa-linkedin-square"></i>
                        </a>
                        <a href="#" class="btn-group twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a href="#" class="btn-group facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <div class="copyright text center">
        <p>&copy; Copyright 2014, <a href="#">Your Website Link</a>. Theme by <a href="https://themewagon.com/"
                target="_blank">ThemeWagon</a></p>
    </div>


    <script type="text/javascript" src="{% static 'js/jquery-1.10.2.min.js'%} "></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script>
        new WOW().init();
    </script>
</body>

</html>

templates/cart/cart_detail.html
{% extends "base.html" %}
{% block body_block %}
{% load static %}
<div class="container"></div>
<h1>Thông tin giỏ hàng</h1>
<table class="table">
    <thead class="danger">
        <th>Sản phẩm</th>
        <th>Tên sản phẩm</th>
        <th>Số lượng</th>
        <th>Đơn giá (vnđ)</th>
        <th>Thành tiền (vnđ)</th>
        <th>Xóa</th>
    </thead>
    <tbody>
        {% for item in cart %}
        <tr class="success">
            <td>
                <a href="{% url 'mystore:product_detail' item.product.pk%}"><img src="{{item.product.image.url}}"></a>
            </td>
            <td>{{item.product.name}}</td>
            <td>
                <form action="{% url 'cart:cart_add' item.product.pk%}" method="post">
                    {{item.update_quantity_form.quantity}}
                    {{item.update_quantity_form.update}}
                    <input type="submit" value="Cập nhật" />
                    {% csrf_token %}
                </form>
            </td>
            <td>{{item.fee}}</td>
            <td>{{item.total_fee}}</td>
            <td><a href="{% url 'cart:cart_remove' item.product.pk%}">
                    Xóa</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

templates/mystore/doc_cookie.html
{{text}}

templates/mystore/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
{% load static %}
<!-- Page Features -->
<div class="row text-center">
    {% if products %}
    {% for value in products %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card">
            <a href="{% url 'mystore:product_detail' value.pk%}"><img class="card-img-top" src="{{value.image.url}}"
                    alt="{{value.name}}"></a>

            <div class="card-body">
                <h4 class="card-title text-primary"> <a
                        href="{% url 'mystore:product_detail' value.pk%}">{{value.name}}</a> </h4>
                <p class="card-text">{{value.description}}<br />{{value.fee}} vnđ</p>
            </div>
            <div>
                <a href="{% url 'mystore:product_detail' value.pk%}" class='btn btn-primary' style="float: center;"> Xem
                    thêm </a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif%}
</div>
{% endblock %}

templates/mystore/product_detail.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block body_block %}
{% load static %}
<!-- Page Features -->
<div class="row text-center">
    {% if product %}
    <div class="container">
        <div class="card">
            <img class="img-responsive" src="{{product.image.url}}" alt="{{product.name}}" width="350" height="350" />
            <div class="card-body">
                <h4 class="card-title">{{product.name}}</h4>
                <p class="card-text">{{product.description}}<br />{{product.fee}} vnđ</p>
            </div>
            <div>
                <form action="{% url 'cart:cart_add' product.pk%}" method="post">
                    {{cart_product_form}}
                    {% csrf_token %}
                    <div class="card-footer">
                        <input type="submit" value="Thêm vào giỏ hàng" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>

    </div>
    {% endif%}
</div>
{% endblock %}